// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using ReferenceDataService.Infrastructure;

#nullable disable

namespace ReferenceDataService.Infrastructure.Migrations
{
    [DbContext(typeof(ReferenceDataDbContext))]
    [Migration("20260920151600_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("ReferenceDataService.Domain.EmissionFactor", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Category")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<decimal>("Co2FactorPerEur")
                        .HasColumnType("decimal(18,4)");

                    b.HasKey("Id");

                    b.HasIndex("Category")
                        .IsUnique();

                    b.ToTable("EmissionFactors");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Category = "Fuel",
                            Co2FactorPerEur = 2.31m
                        },
                        new
                        {
                            Id = 2,
                            Category = "Electricity",
                            Co2FactorPerEur = 0.45m
                        },
                        new
                        {
                            Id = 3,
                            Category = "Flights",
                            Co2FactorPerEur = 2.50m
                        },
                        new
                        {
                            Id = 4,
                            Category = "PublicTransport",
                            Co2FactorPerEur = 0.10m
                        },
                        new
                        {
                            Id = 5,
                            Category = "OfficeSupplies",
                            Co2FactorPerEur = 0.20m
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
