<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="MassTransit.RabbitMQ" Version="8.5.4" />
    <PackageReference Include="Microsoft.AspNetCore.OpenApi" Version="10.0.10" />
    <PackageReference Include="Microsoft.EntityFrameworkCore.Design" Version="10.0.0">
      <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
      <PrivateAssets>all</PrivateAssets>
    </PackageReference>
    <PackageReference Include="Microsoft.Extensions.Http.Resilience" Version="9.9.0" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\ESGService.Domain\ESGService.Domain.csproj" />
    <ProjectReference Include="..\ESGService.Infrastructure\ESGService.Infrastructure.csproj" />
    <ProjectReference Include="..\..\..\BuildingBlocks\GreenFinance.Contracts\GreenFinance.Contracts.csproj" />
  </ItemGroup>

</Project>
