apiVersion: v1
kind: ConfigMap
metadata:
  name: greenfinance-app-config
  namespace: {{ .Values.namespace }}
  labels:
    {{- include "greenfinance.labels" . | nindent 4 }}
data:
  Consul__Enabled: "false"
  RabbitMq__Host: "rabbitmq"
  RabbitMq__Username: {{ .Values.rabbitmq.username | quote }}
  RabbitMq__Password: {{ .Values.rabbitmq.password | quote }}
  Redis__ConnectionString: "redis:6379"
