apiVersion: v1
kind: Service
metadata:
  name: mailhog
  namespace: {{ .Values.namespace }}
  labels:
    {{- include "greenfinance.labels" . | nindent 4 }}
spec:
  selector:
    app: mailhog
  ports:
    - name: smtp
      port: 1025
      targetPort: 1025
    - name: web
      port: 8025
      targetPort: 8025
