apiVersion: v1
kind: Secret
metadata:
  name: greenfinance-db-secret
  namespace: {{ .Values.namespace }}
  labels:
    {{- include "greenfinance.labels" . | nindent 4 }}
type: Opaque
stringData:
  SA_PASSWORD: {{ .Values.sqlserver.saPassword | quote }}
  {{- range $name, $svc := .Values.services }}
  ConnectionStrings__{{ $svc.db }}: "Server=sqlserver,1433;Database={{ $svc.db }};User Id=sa;Password={{ $.Values.sqlserver.saPassword }};TrustServerCertificate=True"
  {{- end }}
